### ISSUE TITLE
Unable to load library 'anoncreds_uniffi'

### ISSUE THREAD

**Issue by conanoc** [hyperledger/aries-uniffi-wrappers#18]
I got this error when I tried to run an android kmpp app that uses aries-uniffi-wrapper on android simulator/Intel Mac:
```
java.lang.UnsatisfiedLinkError: Unable to load library 'anoncreds_uniffi':
    dlopen failed: cannot locate symbol "__atomic_is_lock_free" referenced by "/data/app/~~GBvVFDuz2tgjcyGR6lPoiQ==/org.hyperledger.kmppapplication.android-EexD2LmcqyZ0470q6nSBkg==/base.apk!/lib/x86/libanoncreds_uniffi.so"...
    dlopen failed: cannot locate symbol "__atomic_is_lock_free" referenced by "/data/app/~~GBvVFDuz2tgjcyGR6lPoiQ==/org.hyperledger.kmppapplication.android-EexD2LmcqyZ0470q6nSBkg==/base.apk!/lib/x86/libanoncreds_uniffi.so"...
    dlopen failed: cannot locate symbol "__atomic_is_lock_free" referenced by "/data/app/~~GBvVFDuz2tgjcyGR6lPoiQ==/org.hyperledger.kmppapplication.android-EexD2LmcqyZ0470q6nSBkg==/base.apk!/lib/x86/libanoncreds_uniffi.so"...
    Native library (android-x86/libanoncreds_uniffi.so) not found in resource path (.)
     at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
     at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
     at com.sun.jna.Native.register(Native.java:1723)
     at anoncreds_uniffi.UniFFILib.<clinit>(anoncreds_uniffi.jvm.kt:170)
     at anoncreds_uniffi.Verifier$special$$inlined$rustCall$1.invoke(anoncreds_uniffi.common.kt:3383)
...
```
I used `https://maven.pkg.github.com/Indicio-tech/aries-uniffi-wrappers` as a maven repo.
And dependencies:
```
dependencies {
    implementation("org.hyperledger:anoncreds_uniffi:0.1.0-wrapper.2")
    implementation("org.hyperledger:indy_vdr_uniffi:0.1.0-wrapper.2")
    implementation("org.hyperledger:askar_uniffi:0.1.0-wrapper.2")
}
```

@TheTreek Can you take a look at this?

**Comment by TheTreek** [comment]
Was able to replicate this on my intel mac with an android simulator as well. Interestingly it is not an issue when ran on a simulator from an M2 mac or when ran on a physical android device (ArmV7). So it's looking like it's an issue with x86 exclusively. Going to look a bit more into this...

**Comment by conanoc** [comment]
It is only reproduced on Android 11 (and below) x86 simulator. It showes no problem on Android 12 x86 simulator.

**Comment by conanoc** [comment]
I could use Askar functions without any problem on Android 11 x86 simulator.
So, it's dependent on anoncreds, maybe on openssl, I'm not sure.
